### ISSUE TITLE
Can’t use volume buttons from my Symfonisk speaker

### ISSUE THREAD

**Issue by sumadark** [owntone/owntone-server#1094]
Hello everyone,

First I want to thank you for this absolute and wonderful plug-in for Homebridge.
I have just bought an IKEA Symfonisk speaker and it is recognised as an airplay receiver without any probem. I can stream music to it, but I am not able to use the volume buttons on the speaker. Although I can use the play/pause button.
Strange fact, when I push multiple times on volume buttons on the speaker, I can see in forked-daapd webserver app that it’s moving a little bit : I pass from volume 18 to 22, or 18 to 15, but there is no logic.
So, some instructions, sometimes, arrive to forked-daapd, but it’s not enough.
I’m not an expert with developing, so I really need some help.

Thank you!

Suma

**Comment by ejurgensen** [comment]
Please set the log level to debug (in /etc/forked-daapd.conf) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by sumadark** [comment]
Well, don't know hat happened but everything is crashed and not working anymore :

sudo service forked-daapd status
* forked-daapd.service - DAAP/DACP (iTunes) and MPD server, supporting AirPlay a
   Loaded: loaded (/lib/systemd/system/forked-daapd.service; disabled; vendor pr
   Active: failed (Result: exit-code) since Thu 2020-09-17 15:27:09 CEST; 26min 
     Docs: man:forked-daapd(8)
 Main PID: 5846 (code=exited, status=1/FAILURE)

sep 17 15:27:09 raspberrypi systemd[1]: forked-daapd.service: Service RestartSec
sep 17 15:27:09 raspberrypi systemd[1]: forked-daapd.service: Scheduled restart 
sep 17 15:27:09 raspberrypi systemd[1]: Stopped DAAP/DACP (iTunes) and MPD serve
sep 17 15:27:09 raspberrypi systemd[1]: forked-daapd.service: Start request repe
sep 17 15:27:09 raspberrypi systemd[1]: forked-daapd.service: Failed with result
sep 17 15:27:09 raspberrypi systemd[1]: Failed to start DAAP/DACP (iTunes) and M

**Comment by sumadark** [comment]
[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/5240206/forked-daapd.log)

Please find the file in attachment.
Now I have glitched  in sound restransmission on this airplay Speaker, from both ipad/iphone streaming and forked-daapd server streaming.

**Comment by ejurgensen** [comment]
About the sound, there is a large number of retransmit requests in the log, which usually indicates network problems.

With regard to the volume: Could you go to http://[your_server]:3689/api/outputs, note the volume, then try pressing the volume button, and then check the volume again? Then try again. How is the volume changing?

I suspect the problem might come from forked-daapd receiving the volume from the speaker, but not sending it back to command a volume change. This is on purpose, because other speakers didn't seem to expect that, but here it might be different.

**Comment by sumadark** [comment]
Hey,
As I said in the first place, when I push up or down for the volume, first nothing happened then I move from 18 to 21, then I go back to 18, even if I keep pushing on up.

**Comment by ejurgensen** [comment]
Ok, seems like with these speakers it might be necessary to send the volume back as a command. The current implementation specifically avoids doing that, because when I made support for volume change it seemed like it would be a bad idea, given that the speaker in question was changing volume just fine by itself. So if I change the behaviour I'm nervous about breaking other speakers.

I think the way ahead is for me to get hold of Symfonisk and then test with iTunes to see what the reference behaviour is. Might take a while before I can get that done.

**Comment by sumadark** [comment]
Dear  ejurgensen,

Thank you for your answer !
i have decided to use another Homebridge plugin to play music on this Symfonisk speaker, works good so for now, it's ok !
Thank you for your future help with this, I appreciate it 👍 

Have a nice day,


Suma

**Comment by ejurgensen** [comment]
Thanks for the notice, may I ask what you are using instead?

**Comment by sumadark** [comment]
Yep, the Homebridge ZP plugin, to add my Symfonisk speaker in homekit as a TV with different inputs (Sonos app favorites stations). It's quite the same thing I have done with forked-daapd and the Homebridge-cmdSwitch2 plugin, who trigger actions to start radio stations and set airplay on my Symfonisk speaker.

(but even when I set the action "curl -X PUT 'http://192.168.X.XX:3689/api/outputs/57717317878408' --data '{\"selected\":true, \"volume\": 18" >>> to start Airplay on Symfonisk, the specified volume is not applied, onyl last used volume setup from forked-daapd is applied).

**Comment by ejurgensen** [comment]
Should work now
