### ISSUE TITLE
Speed and stability improvements with Pi 4?

### ISSUE THREAD

**Issue by titosantana414** [owntone/owntone-server#1233]
I have a 2 TB collection on a powered usb drive connected to a Raspberry Pi 3 broadcasting to airport expresses throughout the house. I'm on the current build. While Forked-Daapd works very well, it can be slow to respond at times and if I try to search or click around too fast it gets overwhelmed and stops working for a period of time - probably due to the scale of the library. 

My question is whether moving from a Raspberry Pi 3 to a 4 with say 4 gb of memory would significantly improve the performance? Or are there any tweaks to that might make a large library more stable?

Hi, Thanks for all the hard work. Having an always on, affordable and reliable whole home audio solution is really cool and I've enjoyed it for a few years now.

**Comment by ejurgensen** [comment]
Hi, it's hard to say for sure without knowing the bottleneck, but of course chances are that it will improve performance. Some things you might try:
- The server generally only accesses songs3.db and cache.db when you make requests, so the usb drive itself shouldn't affect performance. You can check that these two files (in /var/cache/forked-daapd) are on a fast drive. An SD card should be ok, but personally I keep the files on a ram drive (also to avoid writing too much to the SD card).
- You could test if a Remote app is faster than the web UI - those apps use daap, where the server-side caching and indexing might be more optimized.
- Finally check that the performance degradation isn't simply due to the RPi being busy with something else. You can also see from owntone's log (maybe set it to info level) if anything is going on.
