### ISSUE TITLE
Change librespot default artwork

### ISSUE THREAD

**Issue by mfauvain** [owntone/owntone-server#1295]
Hi, I've set a librespot pipe but I can't get the librespot metadata to work/compile so currently owntone works with the pipe, only with a 'default' artwork that I don't like. 
![210815-095454](https://user-images.githubusercontent.com/14844435/129482788-5fb31c8e-11bf-4922-ae2b-3cd845f41ba9.png)
 
Is there a way to set a default jpg for the owntone pipe input?

**Comment by ejurgensen** [comment]
I can't think of any way of doing that. Note that the image you shared above must be from some online source - either Spotify, Discogs or the Cover Art archive. So maybe you can get rid of it by disabling the relevant source (in the web UI settings).

Are you using librespot because you are using Spotify Connect?

**Comment by mfauvain** [comment]
I was reading through the radio .m3u part where it is possible to override with a 'radio filename'.jpg file and thought it would be possible to say add a spotify.jpg where the spotify pipe file is.
Will try to remove sources on the webUI and see.

Yes, I do use both, the embedded spotify access in owntone and also the librespot pipe to get Spotify Connect working. I still haven't tried the spocon way.
