### ISSUE TITLE
Apple AirPlay devices keep disappearing and reappear

### ISSUE THREAD

**Issue by Cludch** [owntone/owntone-server#1346]
Hey,

I am currently running Owntone 28.2 on unRAID (dockerized linux x64 container).
That setup has been running really well for 1-2 years so far, and I am very grateful for your work on the project!

Nonetheless, since a few days, I have issues with devices not showing up in the frontend or disappearing after popping up for a few seconds.
Since I only have Apple devices right now, I can not rule out, whether the last update for their devices broke something.

A short log excerpt can be found [here](https://gist.github.com/Cludch/e67d5b71d59982caf10f8d3b17840033).
I am unsure, whether the type 47 errors are coming from other mDNS using devices, thus those errors could be ignored (?)

I have also tried to isolate the issue  and checked the updates, new devices, network configuration.
However, nothing has really changed.

The owntone server has always been on a different VLAN than the devices. This has worked well since day one using a mDNS repeater. The network setup has not been touched for over a year.

Would be great so hear from other users experiences or whether anyone has an idea.
Update: After some initial research, I have found some reports about unreliable AirPlay since 15.1. I suspect that Apple has to deliver a fix for that.

**Comment by ejurgensen** [comment]
Those type 47 errors don't appear to be coming from OwnTone, so I can't say much about them. The log also isn't showing any devices disappearing.

The symptoms you describe don't match the reports about Airplay since 15.1 that I have seen, so I think it is to early to count it as an Apple issue.

Maybe you can try if the "permanent" setting in the config resolves the problem (then it would almost definitely be a network mdns issue). Otherwise, try to get some good debug level logging of the issue occuring.

**Comment by Cludch** [comment]
I will try the `permanent` setting and will report back in a few days, whether that has fixed the issue.
If not, I will add a proper debug log, my fault. I thought that there were disconnecting messages, but indeed I missed those. Thanks already!

**Comment by airdrummingfool** [comment]
I was experiencing this exact same issue when I set up OwnTone and a HomePod. It runs in a Docker container with host networking enabled. Setting `permanent = true` in the config file made it show up all the time, and I haven't experienced any issues connecting to it since.

In case it's useful info, I also have tons of `couldn't parse packet` messages in my logs. It's worth noting that I run an mDNS reflector (`avahi-daemon`) on my host to reflect messages between the Docker network and the host network; however owntone does run on the host network (with `network_mode: host`).
```

config-owntone-1  | [2021-11-20T21:52:57Z WARN  libmdns::fsm] couldn't parse packet from 127.0.0.1:5353: class 1440 is invalid
config-owntone-1  | [2021-11-20T21:52:59Z WARN  libmdns::fsm] couldn't parse packet from 172.18.0.1:5353: class 1440 is invalid
config-owntone-1  | [2021-11-20T21:52:59Z WARN  libmdns::fsm] couldn't parse packet from 172.17.0.1:5353: class 1440 is invalid
config-owntone-1  | [2021-11-20T21:52:59Z WARN  libmdns::fsm] couldn't parse packet from 127.0.0.1:5353: class 1440 is invalid
config-owntone-1  | [2021-11-20T21:53:28Z WARN  libmdns::fsm] couldn't parse packet from 172.18.0.1:5353: type 47 is invalid
config-owntone-1  | [2021-11-20T21:53:28Z WARN  libmdns::fsm] couldn't parse packet from 172.17.0.1:5353: type 47 is invalid
config-owntone-1  | [2021-11-20T21:53:28Z WARN  libmdns::fsm] couldn't parse packet from 127.0.0.1:5353: type 47 is invalid
```

**Comment by Cludch** [comment]
Using the `permanent = true` settings fixed the issue for me.
Thanks a lot for helping out so quickly!
