### ISSUE TITLE
Support for iTunes Music Library playlists

### ISSUE THREAD

**Issue by derekatkins** [owntone/owntone-server#1359]
I copied the iTunes data from (my wife's) Mac to Owntone.  This includes her `iTunes Music Library.xml`.  Even though she had a couple dozen playlists defined, none of them show up in the OT list of playlists.  Am I missing a config option to enable that?

I see this in the log:
```
Nov 29 11:29:18 owntone owntone[9501]: [2021-11-29 11:29:18] [ INFO]     scan: Deferred playlist /srv/music/iTunes Music Library.xml
```

**Comment by derekatkins** [comment]
Nope, not showing anything else, at least nothing that matches "playlist".  I do see:
```
[2021-11-29 16:01:07] [  LOG]       db: Database OK with 1812 active files and 7 active playlists
```
But if I click on the "playlists" tab, I don't see anything (except for the smart playlist I created myself, manually).
If I look in the xml file I see multiple 'playlist' entries.  And I see them in the application on the Mac.  But none of them are shown in OT.

**Comment by Porco-Rosso** [comment]
It might be a problem with relative/absolute directories referencing of the files within the xml file?
I ended up having many problems with the xml support. (not least because the new Music.app doesn't seem to care for the xml file anymore)
I ended up just generating .m3u files and making their links relative before syncing over to my server. [Here](https://github.com/Porco-Rosso/iTunes-m3u8-Playlist-Syncer/) is the now outdated script I am using.

**Comment by ejurgensen** [comment]
I have checked the code, and I can't figure out why you are not seeing any further log messages. You should be seeing either of the following (on the normal LOG level):

- `Unchanged iTunes XML found, not processing '%s'`
- `Modified iTunes XML found, processing '%s'`
- `New iTunes XML found, processing: '%s'`
(where %s is the path)

Can you confirm none of those are found in the log? What if you force a scan of the XML with `touch [filename]` - still nothing in the log?

@Porco-Rosso I don't think the issue is related to the paths, since then the log wouldn't be so empty. Also, OwnTone doesn't expect a fully valid path in the XML. The matching works like this: Say the XML has "file://aaa/bbb/ccc/song.mp3". OwnTone will first look just for "song.mp3" in your library, ignoring the path. If only one match is found all is good, and the scan proceeds to next item. If multiple "song.mp3" are found, it makes a new search based on "ccc/song.mp3", and again if counts matches. If multiple, then it tries again with "bbb/ccc/song.mp3". So if you had issues it shouldn't be caused by absolute/relative paths.

**Comment by derekatkins** [comment]
@ejurgensen -- yes, there was an "Unchanged iTunes XML found" in there.
I'll force a rescan, but I want to reduce logging from spam to something a little less... spammy.. so I don't miss the logging.

**Comment by derekatkins** [comment]
So I touched the file, which forced it to reprocess again... and NOW I see a whole list of playlists!!
WTF?   Either it's a bug in 28.2 fixed in master, or the fact that the file was dated months ago played a fact.
How weird.

**Comment by ejurgensen** [comment]
> Either it's a bug in 28.2 fixed in master, or the fact that the file was dated months ago played a fact

Not likely to be any of these. I don't recall any recent changes regarding this, and the absolute value of the file modification time doesn't play a role. Instead, the file modification time is compared with a timestamp that was set the last time the playlist was scanned (see [this code](https://github.com/owntone/owntone-server/blob/master/src/library/filescanner_itunes.c#L863)).

It might be a result of the playlist being first appearing, but for whatever reason being unreadable/unparseble, and then later when it becomes readable it gets ignored because the timestamp is the same.

**Comment by derekatkins** [comment]
Hmm..  I think OT was running when I copied the file(s) over, so it's certainly possible it tried to parse the file before it was fully written.

**Comment by derekatkins** [comment]
Would it make sense to look at file size in addition to file timestamp?

**Comment by ejurgensen** [comment]
The easiest might be to only save a timestamp if the xml was succesfully read and parsed - that would cover both zero size files and partially written files. Would of course mean that OwnTone would keep trying to scan unreadable xml's on start/rescan, but maybe that is ok (or at least better).

**Comment by derekatkins** [comment]
I noticed that when I touched the file OT re-read it immediately..  So clearly it was watching.
I agree that it should only store the timestamp if it is successfully read.  But if it fails to read, it might want to wait a period of time (10s? 60s?) before retrying.
