### ISSUE TITLE
issues with owntone.local when multiple "instances" are running

### ISSUE THREAD

**Issue by kalle2000** [owntone/owntone-server#1367]
Hi,

I have several raspberrys and each one is running owntone (multiroom audio). I am calling the web interface via localip rather than owntone.local. However it seems that a few links on the web interface are using owntone.local instead of local ip (e.g. Authorize spotify web api).

Can you give me a hint how to solve this (besides stopping owntone on all other raspis)?
THX

**Comment by ejurgensen** [comment]
The Spotify authorize url's need to use owntone.local, because Spotify OAuth will redirect back to that. So if the issue is to authorize Spotify (which is just one-off) then set the address you want owntone.local to resolve to in the `hosts` file on the client machine (if you don't want to stop the other instances temporarily).

If the issue is some other use case which isn't one-off then please add details.

**Comment by kalle2000** [comment]
works like a charm for me thx!
