### ISSUE TITLE
Uninstalling owntone-server needed.

### ISSUE THREAD

**Issue by divewiz1** [owntone/owntone-server#1368]
How do i uninstall owntone-server. Purge did not work..
do you have a scrips to do an uninstall on this owntone-server. thanks.

**Comment by ejurgensen** [comment]
Depends how you installed. Since you mentioned "purge" I am guessing it is the RPi deb package installed with apt? That doesn't clean up too much, either due to Debian policy's or my lacking packaging skills. Either way, you can delete "/var/cache/owntone", "/var/log/owntone.log" and "/etc/owntone.conf".

If you installed with "make install" then "make uninstall" should do it.
