### ISSUE TITLE
Cover-Art is shuffled in Apple Music.App

### ISSUE THREAD

**Issue by 3frogx** [owntone/owntone-server#1375]
I have a strange behavior with the shared library in Apple Music.App (on Big Sure 11.6.2). Most albums are displayed with the wrong cover art (from another album). If I activate "artwork_individual", the cover also changes in the tracks of an album.

Everything is OK in the webfrontend and even in iTunes under MacOS 10.13.6, so the problem is not with the music library itself.

I cleared the Music.App caches, but it doesn't change anything.

Greetings, volker

owntone 28.2 on Debian Bullseye

**Comment by ejurgensen** [comment]
This is probably the same issue as #1193. As I understand, it never became clear how the Music.App determines what artwork to show, and thus what could be done to fix it. I also don't have a mac, so can't personally look into it. Thus I closed the issue since the hope of resolving it was slim. Have to do the same here :-(
