### ISSUE TITLE
"Add Next" doesn't work on shuffled queue

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1382]
When I'm listening to a queue of songs, and then search for a specific song, find it and click the vertical ... the options appear to Add or "Add Next". Choosing "Add Next" puts the song into the queue in a seemingly random spot (in my case, up with the previously played songs) and not after the currently playing song.

**Comment by ejurgensen** [comment]
Thanks for notifying, I agree it shouldn't work like that.

**Comment by whatdoineed2do** [comment]
I recal trying to fix this a while back - the _add next_ goes into `db_queue_add_by_query()` where the problem is:

https://github.com/owntone/owntone-server/blob/8f73616750a8b28eee33b21e79103ae87677e329/src/db.c#L5107-L5124

The `queue_item_add_from_file(..., queue_count, ...)` takes 2 position parameters:  a normal queue position (2nd arg) and a shuffle queue position (3rd arg) - for the latter its always the end of the queue where the queue items get shuffled near the bottom of this method.

The apparent fix is to (re)adjust the `shuffle_pos` of existing queue items to insert the requested `position` but it gets a litle messy.
