### ISSUE TITLE
[Feedback] Any testing requests for the new bison parser ?

### ISSUE THREAD

**Issue by richjn** [owntone/owntone-server#1393]
Hi
I've been running the bison_parser1 branch today (great to see this) and have no issues to report so far but are there any specific areas you would like me to concentrate on testing ?

I'm running on Arch Linux but with my own ffmpeg build rather than the somewhat bloated distro version.

Richard

**Comment by whatdoineed2do** [comment]
This would be great.  This https://github.com/owntone/owntone-server/issues/570 was an issue I raised a while back that has been indicative of the other issues I've seen from the antlr parser.

Would be worthwhile trying such malformed strings and queries.

**Comment by richjn** [comment]
Using the curl lines you quoted in your OP I get the same result as you experienced i.e \"Pop\" returns results, single quotes or no quotes just returns Bad Request but no lockups.
I have more time tomorrow I will try to get some more constructive output then.

**Comment by richjn** [comment]
I have run several 'smart playlist query language' tests via the web ui from simple to quite complex and the filter works flawlessly for me across my 55k track collection but only if I comply with the format of README_SMARTPL.md i.e. strings are double quoted, single or no quotes just return 400 Bad Request. It appears the new bison parser behaves in the same fashion the antlr parser.

I'm happy to run any specific tests you may have or test patches.

**Comment by ejurgensen** [comment]
@richjn thanks a ton for testing. Checking that your existing smart playlists still work is exactly the sort of thing that is very good to test. Other than that I suppose it just about using it is normal, and then if you notice anything unexpected (related to making queries/smart playlists) then check if the log says "Could not parse xxxx" (which will show on normal LOG level logging). That could indicate a bug. It is also possible that something is parsed incorrectly, so that the database query becomes incorrect. In that case I would need either a way to reproduce or DEBUG level logging, since that shows the database query.

**Comment by richjn** [comment]
Closing now.
No issues here.
