### ISSUE TITLE
[Question] PTP stream support and Airplay 2 advantages

### ISSUE THREAD

**Issue by hoiz** [owntone/owntone-server#1395]
I tried to connect with forced Airplay 2 (`raop_disable = true`) with the dev version of shairport-sync (with Airplay 2 support). Shairport-sync then reports that no NTP streams are supported, and support is currently not planned (https://github.com/mikebrady/shairport-sync/issues/1407).

I have the following questions about this:
1. Are there plans to support PTP streams as well?
2. Do I have any advantages with Airplay 2 transmission? Or is it no problem to continue transmitting via Airplay 1.
3. Do I have any advantages if I am connected to all devices via Airplay 2?

Thank you!

**Comment by ejurgensen** [comment]
> Are there plans to support PTP streams as well?

I think PTP should be supported, since it's the most common timing method for Airplay 2. But it is tricky, and was also difficult for shairport to implement, requiring a standalone daemon just for that. So I don't know when I will get around to it.

> Do I have any advantages with Airplay 2 transmission? Or is it no problem to continue transmitting via Airplay 1.

Only thing I can think of is that OwnTone's Airplay 2 uses lossless compression, whereas Airplay 1 is uncompressed. So there is a bandwidth advantage, if your wifi is constrained.

> Do I have any advantages if I am connected to all devices via Airplay 2?

Other than bandwidth, then no, not currently. OwnTone also still defaults to AirPlay 1 if the speaker supports it. It will be a different story if/when OwnTone gains the ability to use advanced Airplay 2 features, such as group playback.

**Comment by hoiz** [comment]
Thank you for the quick and detailed reply! I love your project and really use it every day!
