### ISSUE TITLE
Feature Request: Spotify connect with new Spotify implementation 

### ISSUE THREAD

**Issue by ministryofsillywalks** [owntone/owntone-server#1412]
I really like the new Spotify integration it's more stable than librespot (at least for me)
However I really like the option to control Spotify playback from the Spotify client on my phone as it highly increased the all important waf. Librespot supported this. 
Are there any plans to add this functionality to the new implementation as well? Or will control only be available from the webui? 
Thanks a lot for the great work you are doing!

**Comment by ejurgensen** [comment]
Haha, yes, the waf is pretty important, and I could also personally gain some extra waf from adding this, so it is definitely on my list. That said, there is some effort required, and I don't know if or when I will get around to it. Of course, the new Spotify integration is big step in that direction, so that helps. And happy to hear that is stable.

There is another old issue on Spotify Connect which is #295 so I will close this one. Feel free to inquire about progress on the other issue once in a while.
