### ISSUE TITLE
What determines when an album has been time_played

### ISSUE THREAD

**Issue by aleszczynskig** [owntone/owntone-server#1418]
Hi, 
I am constructing a search query to pull the last 12 played albums. I notice however that if I play any track from an album, that the time_played field is not updated. Does the whole album need to be played for this field to be updated?

If this is the case, is there any easy query to pull the last 12 played albums where any track from the album has been played or will I need to build some logic into my application to work this out? 

Thanks for any help you can provide.

**Comment by ejurgensen** [comment]
time_played should be updated when playback of a track ends. I made a quick test, and it seemed to work. How are you checking if the field is updated? On debug level logging you will see the query that does it as:

`[DEBUG]       db: Running query 'UPDATE files SET play_count = play_count + 1, time_played = 1644959557, seek = 0 WHERE id = 68;'`

I also tried making a query that would get the last 12 albums, like so:
`http://localhost:3689/api/search?type=album&expression=media_kind+is+music+order+by+time_played+desc&limit=12`

That didn't give me the expected result, however. I checked the resulting SQL query:
`SELECT  g.id, g.persistentid, f.album, .... MAX(f.time_played), MAX(f.seek) FROM files f JOIN groups g ON f.songalbumid = g.persistentid WHERE f.disabled = 0 AND f.media_kind = 1 GROUP BY f.songalbumid  ORDER BY f.time_played DESC LIMIT 12 OFFSET 0;`

It looks like that query may have an error in it since it has order by time_played, and perhaps it should be by MAX(time_played).

**Comment by aleszczynskig** [comment]
I wasn't checking the field. I was just running the query to retrieve the last albums played, limited to 12 and noticed that the albums aren't updating when I play a subset of tracks from any album. This may be the desired functionality in which case I presume the last albums played will update once an entire album has been played (within a period of time or that all tracks are played sequentially?) however I was hoping it would update based upon any track in that album which has been played recently. 

Are my expectations incorrect or is this a bug as you detailed?

**Comment by ejurgensen** [comment]
I'm thinking it's a bug and not desired functionality. Not 100% sure, but I suspect that the ordering is based on a random track's time_played value from each album. So it wouldn't be that you need to play the entire album, it would be that you need to play the right random track. I'll look a bit more into this and get back.

**Comment by ejurgensen** [comment]
The above should fix the issue. Not a particularly pretty fix, but the other solutions I could think of were even worse.

Hope you can test it.

**Comment by aleszczynskig** [comment]
Thank you. I give it a try.

**Comment by ejurgensen** [comment]
Found a problem with the fix, it wouldn't work with type=composer and order by time_played. I've made a new attempt at a fix that I have pushed to the branch/PR.

**Comment by aleszczynskig** [comment]
Thank you. I have not had a moment to look at this yet but I will try tomorrow.

**Comment by aleszczynskig** [comment]
Just run a quick test and for my use case it appears to work correctly. Thank you for the fix.
