### ISSUE TITLE
Playback from pipe

### ISSUE THREAD

**Issue by ssaferga** [owntone/owntone-server#1424]
Hi,

I use librespot to play spotify to a pipe and owntone listens to that pipe. The problem is that owntone plays that too fast. If i shut down owntone, and listen to the same pipe with snapcast it works fine, starting up the owntone again everything plays too fast again.  Maybe it would work if there is a way to set the samplerate that owntone should use to read the pipe?

**Comment by ejurgensen** [comment]
Can you add some details as to why you conclude that playback is too fast?

**Comment by ssaferga** [comment]
Also, the time line in the spotify client is running away (10sec irl turns out to be ex. 1min)

**Comment by ejurgensen** [comment]
There is no mechanism in owntone that will accelerate playback like you observed. The pipe input is quite simple, owntone will read whatever is written to it, buffer it internally and then play that at a fixed rate (default 44100). So if you are hearing high speed music it must be because librespot is skipping some audio (which would match what you see in the client).

A guess would be that librespot is expecting the consumer to set the playback speed. By that I mean that it writes whenever the pipe (which has a fix buffer size) is available to write. However, owntone reads "greedily" to fill its buffers, so the pipe is mostly always ready to write. Then maybe librespot thinks it is getting behind, and thus accelerates playback. If that is the case I can't think of a solution, and I'm inclined to say that the issue is with librespot. But this is just a guess. I recall having tested with librespot some time ago, and didn't see this issue, so perhaps something else is going on.

**Comment by ssaferga** [comment]
Interesting! Your guess sounds reasonable with what I experience. I will take a look at the librespot end instead then.

Thanks for the quick replies!

**Comment by ejurgensen** [comment]
You could test the guess by letting librespot write to pipe where you on the command line read and discard everything. Maybe `cat librespotpipe > /dev/null`. If it accelerates it would confirm.

**Comment by ssaferga** [comment]
I run the librespot in dockstation, so i just got permission denied trying to do that.
However I also have a mopidy that plays to a pipe, and get the same result,  everything plays fast.
