### ISSUE TITLE
rpiplay won't accept connections after owntone connects

### ISSUE THREAD

**Issue by frankusb** [owntone/owntone-server#1440]
Not sure which side the problem is on but [rpiplay](https://github.com/FD-/RPiPlay) will not accept connections after owntone tries to connect. See issue [337](https://github.com/FD-/RPiPlay/issues/337).

**Comment by ejurgensen** [comment]
When owntone sees an Airplay target it will make a test connection to it, just to check that it is connectable. This is to avoid listing speakers that wouldn't work. From the log it could look like rpiplay quits if a client makes a connection and then disconnects, thus causing what you see. If you build yourself you can test this theory by removing the `MDNS_CONNECTION_TEST` flags in raop.c and airplay.c.

If this is correct I would the say the issue is with rpiplay. I don't see why a server would quit from this.

**Comment by frankusb** [comment]
That did change the behavior. Now I can connect to RPiPlay from an ipad as long as I don't try to connect from owntone. If I try to connect from owntone I get:

`[2022-04-04 08:19:35] [  LOG]     raop: No response from 'RPiPlay' (2600:1700:3f7a:3dc0::1a) to OPTIONS request
[2022-04-04 08:19:35] [  LOG]   player: The AirPlay 1 device 'RPiPlay' failed to activate
[2022-04-04 08:19:35] [  LOG]      web: JSON api request failed with error code 500 (/api/outputs/70342239488)`

**Comment by ejurgensen** [comment]
If audio-only is ok, I would recommend shairport-sync. It should work with OwnTone.

**Comment by frankusb** [comment]
I use shairport-sync, it's wonderful. I was trying to expand my horizons with video. The workaround is OK. I wanted to experiment and will be able to do so.

**Comment by frankusb** [comment]
Further experimentation has shown that the behavior is not specific to owntone, the same happens if I connect from the Macbook Pro sound icon in the menu bar.

**Comment by ejurgensen** [comment]
Thanks for following up
