### ISSUE TITLE
Translation of the Web UI

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1458]
Even if the web UI is simple enough for user to understand how to use it without having much English knowledge, it would be, however, great to have the ability to translate the UI.
Is there a preferred JS library that should be used for localization / internationalization (i18n)?

**Comment by chme** [comment]
I think the standard library for internationalization for Vue.js applications is "Vue I18n" <https://vue-i18n.intlify.dev/>.
Would be nice to have support for different languages in the web UI ... if you want to implement support for it, that would be much appreciated :-)

**Comment by hacketiwack** [comment]
Just to let you know that I'm currently working on this translation.
It shouldn't be long until we have a first version.
I will include French at first.

**Comment by chme** [comment]
Thanks for implementing this! I have merged your changes.

Maybe we should add a default language setting into the owntone.conf file, to allow users to define which language should be used. And additionally store the selected language in the browsers local storage, so that if a user changes the language on one device it will keep this selection (overriding the default)?
