### ISSUE TITLE
Controlling Spotify from Spotify App or Home Assistant

### ISSUE THREAD

**Issue by ocywob** [owntone/owntone-server#1463]
Hi there,

First of all, thanks for the great piece of software. I use owntone with Airport Express and PulseAudio bluetooth to stream music through different speakers in the same time. 

Now I'm trying to find a solution to search and play music with Owntone but I'd like to use Home Assistant interface or Spotify app for this. 

I thought about 2 possible solution:

1- Using my own Client and Secret ID I created from "Spotify for developers". So that I can control the music over the cloud. Is this something not possible?

Home Assistant Spotify integration has a similar solution and it works when I want to control my music over the Spotify app in real-time.

I tried to change the client and secret keys from /src/library/spotifyweb_api.c but I guess I also need to compile it? Is there an easy way to change Spotify secret and client keys?

2- Using a media card with "browse" support home-assistant also could work. I don't know why but forked-daap integration on home assistant is saying "Integration does not support browsing media ". I know this is not your topic but any feedback would be appreciated.

Thanks!

**Comment by ejurgensen** [comment]
I don't know much about Home Assistant, but it sounds like it might support Spotify Connect (possibly via librespot?). Spotify Connect makes it possible to control a speaker (or something speaker-ish) via the Spotify app. I still haven't gotten around to adding Spotify Connect to OwnTone (see issue #295), so that's not an option. Setting your own keys won't change that.

And yes, I don't know about number 2.

I'll close the issue since Spotify Connect already has an issue.
