### ISSUE TITLE
Can't create playlist

### ISSUE THREAD

**Issue by rainerstandke** [owntone/owntone-server#1485]
Hello, 

I am using version 28.3 on rpi, and I have this in my .conf:
`allow_modifying_stored_playlists = true`
`default_playlist_directory = "createdPlaylists"`

I have created a directory `createdPlaylists` in one of the library directories.
The user is set to: `uid = "root"`, and the directories in the path to the default directory is `root`, and then a my regular user account, where all directories are world-readable, and writable.

Not getting a `Save` button in the queue screen in the web UI, and a CURL to the config endpoint returns:
`"allow_modifying_stored_playlists": false,`
`"use_libspotify": false`

Any thoughts about what's going wrong here? What is the recommended user permissions setup?

Thanks!

**Comment by chme** [comment]
Hi, 

I think the problem is that an absolute path is expected for `default_playlist_directory` in the conf file. Could you check if this makes the save button appear?

You could also check the log, the following entries should be in it (level warn/log):

- `Non-writable playlist save directory`
- `Invalid playlist save directory, disabling modifying stored playlists`

As part of the log message the resolved path to the default playlist directory is printed.

**Comment by rainerstandke** [comment]
Hello Christian,

thank you very much for your expedient reply - it hit the spot! A full path starting with`/` does let me save the Queue as a playlist. 

The comment in the config file suggests that those saved lists should be editable & deletable? That seems to not be happening - have not found how to make that happen in the web UI.

It might be a good idea to mention the path needs to be absolute in the default config file?

Thanks agin for your help!

**Comment by whatdoineed2do** [comment]
@chme - should we make this like the /podcast stuff and relative to the (first) library directory?  i have some recollection that perhaps i left this outside because there was no ability to delete playlists and not to have the library cluttered with lots of user created playlists.

Perhaps also on that, the server can auto delete playlists in the playlists dir that have zero entries.
