### ISSUE TITLE
Conflict between OwnTone and TimeMachine (Bonjour)

### ISSUE THREAD

**Issue by braunsch** [owntone/owntone-server#1495]
I am trying to use my Synology NAS (DSM 7.1) for both OwnTone (iTunes music server) and for backing up my MacBook using Time Machine. 
There appears to be a conflict of OwnTone with Bonjour on the Synology:

- If I _deactivate all Bonjour services_ (Control Panel > File Services > Advanced > Enable Bonjour Service discovery), Time Machine on my Mac will not find the Synology as a backup disk (it keeps searching for the backup disk). Bonjour, so I have read, is required for TimeMachine to work.
- If I _activate_ Bonjour, OwnTone will not work anymore. The library shows up on iTunes Remote, but it is grey and cannot be selected. 

The OwnTone log shows the same series of entries, exactly every 20 seconds: 

> 19:26:00	[2022-06-06 02:26:00] [  LOG]     mdns: Avahi state change: Client collision
> 19:26:00	[2022-06-06 02:26:00] [  LOG]     mdns: Avahi state change: Client registering
> 19:26:20	Withdrawing address record for 172.17.0.1 on docker0.
> 19:26:20	Withdrawing address record for 169.254.43.150 on eth1.
> 19:26:20	Withdrawing address record for 192.168.1.210 on eth0.
> 19:26:20	Withdrawing address record for ::1 on lo.
> 19:26:20	Withdrawing address record for 127.0.0.1 on lo.
> 19:26:20	Host name conflict, retrying with OwnTone-43
> 19:26:20	Registering new address record for 172.17.0.1 on docker0.IPv4.
> 19:26:20	Registering new address record for 169.254.43.150 on eth1.IPv4.
> 19:26:20	Registering new address record for fe80::9209:d0ff:fe06:5373 on eth0.*.
> 19:26:20	Registering new address record for 192.168.1.210 on eth0.IPv4.
> 19:26:20	Registering new address record for ::1 on lo.*.
> 19:26:20	Registering new address record for 127.0.0.1 on lo.IPv4.
> 19:26:20	[2022-06-06 02:26:20] [  LOG]     mdns: Avahi state change: Client collision
> 19:26:20	[2022-06-06 02:26:20] [  LOG]     mdns: Avahi state change: Client registering
> 19:26:40	Withdrawing address record for 172.17.0.1 on docker0....

This way, I would have to choose: Either back up my computer to the NAS, or listen to my music... 

Is there any way to mitigate this? 

(This may have also been the reason for my problem with disks not going to sleep: The Synology NAS, by default, comes with Bonjour activated. I found a hint about conflicts between OwnTone/forked_daapd and Bonjour, deactivated Bonjour - and all seemed to work, including my disks going to sleep. Later, I wanted to set up my Time Machine, I had to re-activate Bonjour - and the "disks not sleeping" problem is back, too)

**Comment by ejurgensen** [comment]
I think a conflict between mdns daemons on your Synology might be the cause of this, maybe made more complicated by Docker being part of the setup.

OwnTone depends on Avahi for mdns. I don't know how that works via Docker, but I can imagine that the setup is conflicting with the mdns daemon that the Time Machine service depends, whether it is is Avahi or not  I see Avahi reports "Client collision".

Since Synology is not an Apple device, I suppose it is not Time Machine and Bonjour proper that it is running?

The problem is very particular to your setup, and since I don't know exactly what is causing it, there isn't much help I can offer. There isn't any way around the Avahi dependency.
