### ISSUE TITLE
Request: Stream.mp3 with metadata

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1504]
I recently used the streaming feature more often (to get the Music via Windows or IOS) - and i noticed that vlc (i use on both platforms) does not receive any information about what it gets.
Maybe i am doing sth wrong - but maybe this would be worth implementing....

**Comment by ejurgensen** [comment]
I recall @whatdoineed2do added this at some point, so I would have thought it worked. Any ideas, @whatdoineed2do?

**Comment by whatdoineed2do** [comment]
The metadata is sent to client using `icy-metadata` but the client has to ask for it when starting the request.

it would appear in this instance that `vlc` does not do this - in which case we can;t do anymore (we can't forcible send the metadata injected in the stream because the client wont know to parse it out and the client play the metadata as audiable glitches).  I seem to recall making some comment in the commit or the PR about VLC not requestingthis.

@LordMyschkin you can verify if hte client is requesting this by the `INFO` log lines `Beginning mp3 streaming...`

```
  param = evhttp_find_header( evhttp_request_get_input_headers(req), "Icy-MetaData");
  if (param && strcmp(param, "1") == 0)
    require_icy = true;

  DPRINTF(E_INFO, L_STREAMING, "Beginning mp3 streaming (with icy=%d, icy_metaint=%d) to %s:%d\n", require_icy, streaming_icy_metaint, address, (int)port);
```

**Comment by whatdoineed2do** [comment]
This thread https://code.videolan.org/videolan/vlc/-/issues/21057#note_313220 seems to confirm VLC does not support `icy-metadata`

**Comment by LordMyschkin** [comment]
I tried on windows:
Media player: no Metadata
VLC: no Metadata
NetRadio: no Metadata shown
Winamp: Shows Metadata
Clementine: Shows Metadata (but does not play stream properly)
**Foobar2000:** Shows Metadata, works great - I think I'll stick with that, works on IOS, MacOS and Windows - I recommend that one highly!
