### ISSUE TITLE
Track de-duplication: identical tracks appear twice

### ISSUE THREAD

**Issue by minfrin** [owntone/owntone-server#1518]
Testing owntone by asking it to import two separate libraries, we see sensible behavior on the albums - despite two album directories existing for a duplicate we get one album.

We don’t see same for duplicated tracks, these appear twice.

To clarify, “duplicated” means a bit-for-bit copy of the same file (identical hash), rather than a song encoded two different ways, which I recognise would be two different tracks.

Is there an option to mark dups to be ignored so they appear once in the index?

![CD4E1AE9-5500-457C-8659-7571FE62812F](https://user-images.githubusercontent.com/1331788/178141687-f2c811bf-0438-4475-ba07-0c66d6c70ec9.png)

**Comment by ejurgensen** [comment]
No, there isn't such an option. Maybe there should be, but I can't think of an easy way to add it.

**Comment by minfrin** [comment]
In theory we need to track some kind of hash to store alongside each track in the database. The hash could be a SHA hash, but that means scanning the library all the way through. Using the name and length of the file as a hash is probably good enough - two files with same name and same length, probably same file.

Then, in the database queries, use `SELECT DISTINCT` or similar to remove dups. No need to make the dups vanish across the codebase, you just want them to not appear in listings.

**Comment by ejurgensen** [comment]
A good solution to this would be rather complicated, since I would say it should also deal with duplicate tracks that aren't necessarily exactly byte-for-byte similar. Say you have the same track both as mp3 and flac, or locally and on Spotify. In this case you would probably want OwnTone to pick the best one.

Also, there are different views to consider. Sometimes you would want to show the best track for an album, but for a filesystem view you would want to show all the present tracks.
