### ISSUE TITLE
Cannot connect to web interface (browser tries for a long time, and then fails)

### ISSUE THREAD

**Issue by HubKing** [owntone/owntone-server#1531]
I am using the AUR build which includes web interface. In the config file, `admin_password` is set, ` websocket_port = 3688`, and `ipv6 = no`. `websocket_interface`, `trusted_networks`, and `bind_address` are commented out. If I try to connect to the web interface, the browser tries to connect for a very long time (maybe 1min+), and then fails with "The connection to the server was reset while the page was loading."

I tried connecting on both the same computer (running OwnTone) and a remote computer. Both had the same problem. The server itself is working (can play music), and I do not find any error message regarding the web interface in the log. What could be the problem?

**Comment by ejurgensen** [comment]
I haven't tried this build, but it sounds like an issue with libwebsockets. Not sure what it might be, though. Perhaps the log has a hint?

**Comment by HubKing** [comment]
The default config file had ` websocket_port = 3688`, so I tried to connect it to port 3688, but when I viewed [the documentation page](https://owntone.github.io/owntone-server/clients/web-interface/), it was using port 3689, so I tried to connect to that port, and it worked. Why is it so?

**Comment by ejurgensen** [comment]
That's because a websocket port is not the same as a web server port. The web server is on 3689, so that's what you tell the browser. The browser will then automatically connect to 3688 to get live updates, which is what websockets are for. 

If you click the speaker list in the UI you should see a http streaming option (start playback first). Worked on my iPhone just now, but had to press the open in new tab icon.
