### ISSUE TITLE
[web] Removing Podcasts added by URL

### ISSUE THREAD

**Issue by dev1981** [owntone/owntone-server#1616]
Hello,

i added two podcats using the "Add Podcast RSS feed URL".
Now i am not able to remove them anymore.
Selecting them and clicking "Remove Podcats" does nothing.
Can i delete them from console somehow?

and in addition on the playlist tab of the Web Ui i have an PL item which only shows the icon. I dont have any playlists yet.
if i klick on it the logs writes:

[2023-06-01 10:03:58] [  LOG]      web: Unrecognized path '/api/library/playlists/undefined' in JSON api request: '/api/library/playlists/undefined'
[2023-06-01 10:03:58] [  LOG]      web: Unrecognized path '/api/library/playlists/undefined/tracks' in JSON api request: '/api/library/playlists/undefined/tracks'

**Comment by ejurgensen** [comment]
Yes, seems there is a problem removing RSS from the web UI. @hacketiwack is this something you can check? Looks to me like the web UI isn't making any deletion request, not sure why. Maybe you can also check the last issue with the "undefined" request?

@dev1981 here's how you can delete the RSS manually:
1. Go to http://l[IP]:3689/api/library/playlists (easiest in Firefox since it formats the json), locate the id of the podcast
2. From command line, run `curl -X DELETE "http://localhost:3689/api/library/playlists/[ID]"`

**Comment by ejurgensen** [comment]
Thanks for the quick fix!
