### ISSUE TITLE
Expose a custom chromecast virtual device for audio routing?

### ISSUE THREAD

**Issue by sriramsv** [owntone/owntone-server#1624]
I had an idea where if owntone broadcasted its own chromecast/airplay virtual device which could be used to dynamically pair other speakers in a proxy manner. This would simplify sharing from mobile devices to multiple speakers without creating static groups on google home/Sonos apps etc.

**Comment by ejurgensen** [comment]
Not sure I completely understand what you mean, could you elaborate? E.g. give a use case example?

**Comment by sriramsv** [comment]
I meant to say if Owncast could broadcast its own Chromecast device ID like `Owntone Speaker` on the network, this can be used by devices on the network to share media to own tone. Then Owntone can internally route it to different speakers around the house based on its setting.

**Comment by ejurgensen** [comment]
Ok, I understand. This would require adding a Chromecast receiver to OwnTone, which is a significant task. I don't even know if there are any open source Chromecast receivers.

With Airplay, what you can do is use shairport-sync as a receiver and let it write the audio via an audio pipe to OwnTone, which can then route to the speakers. So that's kindof like you are thinking of, except using Airplay. If you Google it I think you can find more info on it (maybe try "forked-daapd" if you at first don't find anything).
