### ISSUE TITLE
ID3 rating tag sync

### ISSUE THREAD

**Issue by jptrsn** [owntone/owntone-server#1678]
It would be great to have functionality to read and write to the id3 tag with metadata from owntone. I'm currently using PlexAmp to sync music to my phone and listen when I'm not at home, and I have that set up to sync the rating with the file's id3 tag - I believe it's using the python mutagen library.

It would be amazing to have the ability to read and write the ratings to the files' id3 tags. I've lost all my metadata from my itunes days, and my playlists based on ratings, dates added, played, skipped, and play/skip count are all now starting over from scratch. I would love the ability to write this data directly to the file metadata, so that I can keep all that in sync across my devices and platforms.

Alternatively, a sync solution for android would solve all my problems! :)

**Comment by ejurgensen** [comment]
I think this could be fine to have, but since I don't personally have a need for this, I have to say it won't be high on my todo list.

**Comment by jptrsn** [comment]
I'm poor at writing C, but it feels like this could live in the `filescanner_ffmpeg.c` file, I would just need to extend the struct on line 177 `md_map_generic` to include a rating field and parser? Or would it be in the `md_map_id3` struct, since it needs to be parsed from the tag. (It looks like, from reading comments, that the id3 section is meant for fields that ffmpeg can't handle) Really not sure how to proceed, I wouldn't know where to begin debugging the code. Hopefully this will be a feature that someone else wants too, and can offer a PR.

**Comment by hacketiwack** [comment]
And this would complement what is expected to be implemented in this [work item](https://github.com/owntone/owntone-server/issues/1621).

**Comment by whatdoineed2do** [comment]
I've had this in my local branch for a few months  - it uses the AVDictionary api to write update the media do it but doesnt work for all files (.m4a in my testing) but my library is mostly mp3/flac/m4a.

- fetch rating from db and update (trigged via rest endpoint)
https://github.com/whatdoineed2do/forked-daapd/commit/af52bc0f60f152eb69d7aa454e1923ccb02083bd
https://github.com/whatdoineed2do/forked-daapd/commit/e9c509cdbc17f7eedae4d911ab044930d2253928

- read rating from initial scan (potential overwritting server's own rating update algorithm held in db upon forced library refresh)
https://github.com/whatdoineed2do/forked-daapd/commit/9731c1f68849a8d3a4ece1e9f2188decb3e9f3cb

I didnt push this into a PR because on the db to media sync, i have to disable the library scanning which isnt the prettiest thing but it works

if this is of wider interst - and more importantly approach is ok (i dont want to dedicate time to a null cause) - i'll clean up and send a PR

**Comment by ejurgensen** [comment]
I can't give an priori guarantees about accepting a PR. I can just say that I'm ok with including the feature, so it would be a question of the implementation. How did you (or would you) handle the issue with inotify?

**Comment by whatdoineed2do** [comment]
sure, of course i'm not asking for PR acceptance but agreement that current impl approach is not wildly out of comfort 

`inotify` issue is taken care of (crudely) by `library_deinit()` ahead of the db to file sync of metadata.  looking at disabling `inotify` on the individual files to be updated wasnt trivial with the db watcher stuff

the flow:
* rest endpoint to initiate db rating to file sync
* disable library scanning via `library_deinit()`
* find via db query local library files with rating > 0
** validate mismatch of rating of file vs library
** create new file with updated rating via `AVDictionary` update with temp filename
** move / overwrite existing file
* re-init library scanning via `library_init()`

**Comment by ejurgensen** [comment]
Ok. I agree that disabling inotify entirely is a bit too crude.

Why the extra endpoint instead of just adding a hook to the current rating update? Rating updates could come from other places than the web UI.

**Comment by whatdoineed2do** [comment]
The server process some mpd-like algorithm to update the rating depending on play so integrating with the _rating update_ endpoint gives us a gap - mpd stuff also looks like theres an endpoint for updating rating too.

any thoughts on the inotify disablement?  is it as simple as `db_watch_delete_bypath()` on each file being sync'd and a new 
```
void db_watch_enable_bypath(...)
{
...
  memset(&wi, 0, sizeof(struct watch_info));

#ifdef __linux__
  wi.wd = inotify_add_watch(inofd, path, IN_ATTRIB | IN_CREATE | IN_DELETE | IN_CLOSE_WRITE | IN_MOVE | IN_DELETE | IN_MOVE_SELF);
#else
  wi.wd = inotify_add_watch(inofd, path, IN_CREATE | IN_DELETE | IN_MOVE);
#endif
  if (wi.wd < 0)
    {
      DPRINTF(E_WARN, L_SCAN, "Could not create inotify watch for %s: %s\n", path, strerror(errno));
      return;
    }

      wi.cookie = 0;
      wi.path = path;

      db_watch_add(&wi);
}
```
i thought there were other things to take into account with the watcher tasks

**Comment by ejurgensen** [comment]
> The server process some mpd-like algorithm to update the rating depending on play so integrating with the rating update endpoint gives us a gap - mpd stuff also looks like theres an endpoint for updating rating too.

Yes, I know, and that's why I asked about the endpoint. I didn't mean adding a hook to the rating update endpoint (if you mean "PUT /api/library/tracks"). I don't know exactly at what level to insert the hook. I suppose the lowest level is the db, but that might become ugly.

I would have to look closer at the inotify stuff to really say, but yes, adding and deleting watches by path seems like it could be a reasonable solution.

**Comment by whatdoineed2do** [comment]
i remember now why this becomes more fiddly - the inotify fd belongs to the filescanner module and i didnt want epose that for other peices but given `db_watch_ delete_bypath()` is open its not a problem.

So perhaps the fix to this is filescanner module to add 2x interfaces:
* `file_scan_enable_bypath(const char *)` -> `db_watch_add()`
* `file_scan_disble_bypath(const char *)` -> `db_watch_delete_bypath()`

i'll experiment with this over the next few days
