### ISSUE TITLE
Persistent id for songs

### ISSUE THREAD

**Issue by rainerstandke** [owntone/owntone-server#1709]
Hello,

thanks for this project, I have been a long-time user, and I greatly appreciate everyone's efforts that go into it!

I am building an app that uses the JSON API, and I am wondering how I could possibly uniquely identify tracks in the long run. Is there an identifier that survives library rebuilds? (I noticed that every now and then the list of recently added items changes completely, and I am concerned that things like `album_id`, `album_artist_id`, and `id` could change, and might make it impossible for me to relate owntone songs to entries in my new app's database.)

I m curious about how those 3 ids above are generated. `id` seems a lot like a running count incrementing steadily. What is the source of the other two?

For reference here is a sample of a track that I get from owntone:

`Track(id: 83776, title: "Capri Fischer", title_sort: "Capri Fischer", artist: "Rudi Schuricke & Der Waldo Favre-Chor", artist_sort: "Rudi Schuricke & Der Waldo Favre-Chor", album: "Deutsche Hits, Vol. 3", album_sort: "Deutsche Hits, Vol. 00003", album_id: "822173362457304662", album_artist: "Various Artists", album_artist_sort: "Rudi Schuricke", album_artist_id: "9032501443795729974", composer: nil, genre: "German Pop", comment: nil, year: 2006, track_number: 10, disc_number: 1, length_ms: 197416, date_released: Optional("2006-01-15"), media_kind: "music", data_kind: "file", path: "/mnt/MusicStick/iTunes/iTunes Media/Music/Compilations/Deutsche Hits, Vol. 3/10 Capri Fischer.m4a", uri: "library:track:83776", artwork_url: "/artwork/item/83776")`

Thanks for your help!

**Comment by ejurgensen** [comment]
Sounds interesting. I would say the answer depends on how persistent you need the ID's to be:

- The track ID is set by the database as an autoincrement when a new row is added. Tracks are added as new rows when they are first detected, so after that the IDs should stay the same. If the user deletes the db (if that's what you mean by rebuilds library) then the ID's will change. I don't remember what happens if files are moved within the library (you could test that).
- Both album_id and album_artist_id are hashes of various metadata properties. So they will be the same even if the db is deleted and recreated, but note that the hashing rules can change between versions of OwnTone.

If these aren't persistent enough, you could go for a solution where you use the path as a persistent track identification, and then look up OwnTone ID's via the API. However, even a path can change if the user decides to move files around.
