### ISSUE TITLE
owntone has a huge problem

### ISSUE THREAD

**Issue by Yumega** [owntone/owntone-server#1715]
The songs have same album name and same album artist name, ridiculous, owntone can't sort them into the same album.
the crazy thing is every other unknown tags of the songs should be the same. 
even mp3tag can't deal with this.

if you don't believe what I said above, you can download UK-Top-100-Singles-Chart, use mp3tag to edit album name and album artist name into the same. 

https://1337x.to/torrent/5980148/The-Official-UK-Top-100-Singles-Chart-08-February-2024-Mp3-320kbps-PMEDIA/

owntone will only display 3 songs in the album 
![image](https://github.com/owntone/owntone-server/assets/61570667/7d608526-3065-4de7-9d8a-354af3df10bb)

but other selfhost music tool like navidrome can display all of them within a super fast time
![image](https://github.com/owntone/owntone-server/assets/61570667/2f680759-5b7c-4d72-9efa-3faa9d5afd54)

**Comment by hacketiwack** [comment]
Hi @Yumega, I strongly suggest that you use [MusicBrainz Picard](https://picard.musicbrainz.org) to tag your music.

**Comment by hacketiwack** [comment]
Certain, if the album is in the MusicBrainz's database, then you can tag it.
But it seems this album is nothing official. Probably a fan made a compilation by themselves.
In any case, I downloaded right now the songs that you provided and they are **not** in an album.

Moreover, if you have tagged them in one album (which is not really correct because they are not in any official album IMHO), then you have to make sure that they have one of these elements in common:

- MusicBrainz Album Id
- MUSICBRAINZ_ALBUMID
- MusicBrainz Release Group Id
- MusicBrainz DiscID
- CDDB DiscID
- CATALOGNUMBER
- BARCODE

This is how OwnTone groups the releases.

**Comment by hacketiwack** [comment]
> I still think it's owntone's problem, because navidrome and Rigelian can display all the tracks perfectly after edit by mp3tag. only owntone itself can't display all of them.

I would say that these other software do incorrect assumptions by assuming that an album is just distinguished by its name.
I have several albums with the same name. They can be from different artists or different releases of the same album.
Therefore, the only way to split them is certainly not using the name, but to use a unique identifier.

In my opinion, the songs you downloaded are just a collection of single releases and they should be considered as separate albums. This is, by the way, how MusicBrainz Picard identifies them.

Then, my suggestion would be to create a playlist called UK 100 Hits February (whatever name you'd like)
