### ISSUE TITLE
Automaticly reconnect to chromecast

### ISSUE THREAD

**Issue by nickdevnl** [owntone/owntone-server#1777]
So I got an issue when using chromecast it disconnects after around 7-8 hours.
Is it possible to automaticly reconnect to a certain audio group when its reachable again?

`Jun 28 17:00:19 raspberrypi owntone[81402]: [2024-06-28 17:00:19] [  LOG]     cast: Send error for 'AUDIO': Network is unreachable
Jun 28 17:00:20 raspberrypi owntone[81402]: [2024-06-28 17:00:20] [  LOG]   player: Output device disappeared during streaming!`

**Comment by ejurgensen** [comment]
OwnTone will try to reconnect after 5 seconds on connection loss, but it doesn't support a "pending reconnect", i.e. connect when the device reappears. This is difficult to implement because when speakers come back online they often do so "gradually", e.g. announce themselves before actually being fully up and ready to connect to.

In your case, the reconnect after 5 seconds is also not attempted, because to OwnTone's internal player the device was completely removed, so there is nothing to reconnect to.

So if you can't fix the root cause of the network becoming unreachable then I think your only option is some cron job that resurrects the speaker. If the speaker is always on then "mpc enable AUDIO" each minute should be fine, but if it's not always on, it becomes a bit more complicated since you need to query the state.
